### ISSUE TITLE
How to add credits to an image?

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#95]
For images used in blog posts.

**Comment by aschrijver** [comment]
For the header image that is specified directly in the frontmatter you can use `caption` and specify a text. This appears at the bottom-right corner of the header image. Example:

```yml
header:
  image: /assets/images/blog/cellphone-use-in-traffic/cellphone-use-in-traffic.jpeg
  teaser: /assets/images/blog/cellphone-use-in-traffic/cellphone-use-in-traffic-ogimage.jpeg
  og_image: /assets/images/blog/cellphone-use-in-traffic/cellphone-use-in-traffic-ogimage.jpeg
  caption: This is a test
```

For images that are inline in the content of the blog post there are the following options:

- [Image with Caption](https://mmistakes.github.io/minimal-mistakes/post%20formats/post-image-caption/) ([source](https://raw.githubusercontent.com/mmistakes/minimal-mistakes/master/docs/_posts/2010-08-07-post-image-caption.md))
- [Image linked with Caption](https://mmistakes.github.io/minimal-mistakes/post%20formats/post-image-linked-caption/) ([source](https://raw.githubusercontent.com/mmistakes/minimal-mistakes/master/docs/_posts/2010-08-06-post-image-linked-caption.md))
